services:

  svc-daniel:
    image: casvill/cali-service:v1
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      STUDENT_NAME: Daniel
      HOOD: "Los Alcazares"
    networks:
      - los-alcazares
      - cali
    volumes:
      - biblioteca-del-pueblo:/var/log/app
    ports:
      - "0:8080"

  svc-tina:
    image: tina237/cali-service:v1
    environment:
      STUDENT_NAME: "Valentina Nitola"
      BARRIO: "Ciudad Jardin"
    networks:
      - ciudad-jardin
      - cali
    volumes:
      - biblioteca-del-pueblo:/var/log/app
    ports:
      - "0:8080"

networks:
  los-alcazares:
  ciudad-jardin:
  cali:

volumes:
  biblioteca-del-pueblo: